find_missing_people/find_missing_people/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('listings/', include('listings.urls', namespace='listings')),
    path('', include('pages.urls', namespace='pages')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('contacts/', include('contacts.urls', namespace='contacts')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

find_missing_people/listings/urls.py
from django.urls import path

from . import views

app_name = 'listings'

urlpatterns = [
    path('', views.listings_all, name='listings_all'),
    path('<int:listing_id>/', views.detail, name='detail'),
    path('search/', views.search, name='search'),
]

find_missing_people/pages/urls.py
from django.urls import path

from . import views

app_name = 'pages'

urlpatterns = [
    path('', views.index, name='index'),
    path('map/', views.map, name='map'),
    path('request/', views.request, name='request'),
]

find_missing_people/templates/pages/index.html
{% extends 'base.html' %} 

{% load humanize %}

{% block title %} | Welcome {% endblock %}

{% block content %}

<section id="page">
  <div class="container text-center">
    <div class="home-search p-5">
      <div class="overlay p-5">
        <h1 class="display-4 mb-4">
          Help Finding Missing People !
        </h1>
        <p class="lead">You can search by location, year and sex (This is just a project website)</p>
        <div class="search">
          <form action="{% url 'listings:search' %}">
            <div class="form-row">
              <div class="col-md-4 mb-3">
                <label class="sr-only">City</label>
                <input type="text" name="city" class="form-control" placeholder="City">
              </div>

              <div class="col-md-4 mb-3">
                <label class="sr-only">State</label>
                <select name="state" class="form-control">
                  <option selected="true" disabled="disabled">State (All)</option>
                  {% for abbrev, state in state_choices.items %}
                    <option value="{{ abbrev }}"> {{ state }} </option>
                  {% endfor %}
                </select>
              </div>

              <div class="col-md-4 mb-3">
                <label class="sr-only">sex</label>
                <select name="sex" class="form-control">
                  <option selected="true" disabled="disabled">Sex</option>
                  {% for letter, sex in sex_choices.items %}
                    <option value="{{ letter }}"> {{ sex }} </option>
                  {% endfor %}
                </select>
              </div>
            </div>
            <div class="form-row">
              <div class="col-md-6 mb-3">
                <label class="sr-only">start_year</label>
                <select name="start_year" class="form-control">
                  <option selected="true" disabled="disabled">start_year</option>
                  {% for start_year_key, start_year_val in start_year_choices.items %}
                    <option value="{{ start_year_key }}"> {{ start_year_val }} </option>
                  {% endfor %}
                </select>
              </div>
              <div class="col-md-6 mb-3">
                <label class="sr-only">end_year</label>
                <select name="end_year" class="form-control">
                  <option selected="true" disabled="disabled">end_year</option>
                  {% for end_year_key, end_year_val in end_year_choices.items %}
                    <option value="{{ end_year_key }}"> {{ end_year_val }} </option>
                  {% endfor %}
                </select>
              </div>
            </div>
            <button class="btn btn-secondary btn-block mt-4" type="submit">Submit form</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>

{% include 'partials/_alerts.html' %}

<section id="listings" class="py-5">
  <div class="container">
    <h3 class="text-center mb-3">New Missing People</h3>
    <div class="row">

      {% if listings %}
        {% for listing in listings %}
          <div class="col-md-6 col-lg-4 mb-4">
            <div class="card listing-preview">
              <img class="card-img-top" src="{{listing.photo_main.url}}" alt="">
              <div class="card-img-overlay">
              </div>
              <div class="card-body">
                <div class="listing-heading text-center">
                  <h4 class="text-primary">{{ listing.name }}</h4>
                  <p>
                    <i class="fas fa-map-marker text-secondary"></i> {{ listing.city }}, {{ listing.state }}</p>
                </div>
                <div class="row py-2 text-secondary">
                  <div class="col-6">
                    <i class="fas fa-user"></i> {{ listing.user }}</div>
                </div>
                <div class="row text-secondary pb-2">
                  <div class="col-6">
                    <i class="fas fa-clock"></i> {{ listing.list_date }}</div>
                </div>
                <hr>
                <a href="{% url 'listings:detail' listing.id %}" class="btn btn-primary btn-block">More Info</a>
              </div>
            </div>
          </div>
        {% endfor %}
      {% else %}
        <div class="col-md-12">
          <p>No Missing People</p>
        </div>
      {% endif %}
    </div>
  </div>
</section>

<section id="services" class="py-5 bg-secondary text-white">
  <div class="container">
    <div class="row text-center">
      <div class="col-md-4">
        <i class="fas fa-file-video fa-4x mr-4"></i>
        <hr>
        <h3>Automatic Searching People On Videos</h3>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt, debitis nam! Repudiandae, provident iste consequatur
          hic dignissimos ratione ea quae.</p>
      </div>
      <div class="col-md-4">
        <i class="fas fa-images fa-4x mr-4"></i>
        <hr>
        <h3>People on the images are not real people.</h3>
        <p>All Images are from <a href="https://www.thispersondoesnotexist.com/">thispersondoesnotexist</a></p>
      </div>
      <div class="col-md-4">
        <i class="fas fa-heart fa-4x mr-4"></i>
        <hr>
        <h3>Requesting & Help Finding</h3>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt, debitis nam! Repudiandae, provident iste consequatur
          hic dignissimos ratione ea quae.</p>
      </div>
    </div>
  </div>
</section>

{% endblock %}

find_missing_people/templates/pages/map.html
{% extends 'base.html' %} 

{% load static %}

{% block title %} | Map {% endblock %}

{% block content %}

  <section id="page-inner" class="py-5 text-white">
    <div class="container">
      <div class="row text-center">
        <div class="col-md-12">
          <h1 class="display-4">Map</h1>
          <p class="lead">Check Missing People!</p>
        </div>
      </div>
    </div>
  </section>

  <section id="bc" class="mt-3">
    <div class="container">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="{% url 'pages:index' %}">
              <i class="fas fa-home"></i> Home</a>
          </li>
          <li class="breadcrumb-item active"> Map</li>
        </ol>
      </nav>
    </div>
  </section>

  <section class="py-4">
    <div class="container">
      <div class="row text-center">
        <div class="col-md-12">
          <h2>Missing People Map</h2>
            <div class="form-row">
              <div class="col-md-4 mb-3">
                <label class="sr-only">City</label>
                <input type="text" name="city" class="form-control" placeholder="City" value="{{ values.city }}">
              </div>
              <div class="col-md-4 mb-3">
                <label class="sr-only">State</label>
                <select name="state" class="form-control">
                  <option selected="true" disabled="disabled">State (All)</option>
                  {% for abbrev, state in state_choices.items %}
                    <option value="{{ abbrev }}" {% if abbrev == values.state %} selected {% endif %} > {{ state }} </option>
                  {% endfor %}
                </select>
              </div>
            <button class="btn btn-secondary col-md-4 mb-3" name="city" onclick="searchMissingPeople('{{listing}}', this)">Search</button>
          </div>
        </div>
      </div>
    </div>
    <div id="map"></div>
  </section>

  <section id="help" class="bg-dark text-white text-center">
    <h2 class="display-4">How To Help</h2>
    <h4>Lorem ipsum dolor sit amet consectetur adipisicing elit. Autem velit aperiam, unde aliquid at similique!</h4>
    <hr>
    <a href="{% url 'listings:listings_all' %}" class="btn btn-secondary text-white btn-lg">View Missing People</a>
  </section>

  <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCosvd-S-qpiX5eZM95hPBswc7W2ZTl9c0&callback=initMap"></script>
  <script src="{% static 'js/map.js' %}"></script>
{% endblock %}

find_missing_people/templates/pages/request.html
{% extends 'base.html' %} 

{% load humanize %}

{% block title %} | Welcome {% endblock %}

{% block content %}

<section id="request" class="bg-light py-5">
    <div class="container">
      <div class="row">
        <div class="col-md-6 mx-auto">
          <div class="card">
            <div class="card-header bg-primary text-white">
              <h4>
                <i class="fas fa-check"></i> Request</h4>
            </div>
            <div class="card-body">
                {% include 'partials/_alerts.html' %}
                <form action="{% url 'pages:request' %}" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="name">Name</label>
                        <input type="text" name="name" class="form-control" required>
                    </div>
                    <div class="form-group">
                        <label for="image">Image</label>
                        <input type="file" name="image">
                    </div>
                    <div class="form-group">
                        <label for="sex">sex</label>
                        <select name="sex" class="form-control" required>
                        <option selected="true" disabled="disabled">Sex</option>
                        {% for letter, sex in sex_choices.items %}
                            <option value="{{ letter }}"> {{ sex }} </option>
                        {% endfor %}
                        </select>
                    </div>
                    <div class="form-group">
                    <label for="age">Age</label>
                    <input type="number" name="age" class="form-control" required>
                    </div>
                    <div class="form-group">
                        <label for="city">City</label>
                        <input type="text" name="city" class="form-control" required>
                    </div>
                    <div class="form-group">
                        <label for="state">State</label>
                        <select name="state" class="form-control" required>
                        <option selected="true" disabled="disabled">State (All)</option>
                        {% for abbrev, state in state_choices.items %}
                            <option value="{{ abbrev }}"> {{ state }} </option>
                        {% endfor %}
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="address">Address</label>
                        <input type="text" name="address" class="form-control" required>
                    </div>
                    <div class="form-group">
                        <label for="date">Missing Date</label>
                        <input type="date" name="date" class="form-control" required>
                    </div>
                    <div class="form-group">
                        <label for="description">Other Description</label>
                        <input type="text" name="description" class="form-control" value="None" required>
                    </div>
                    <div class="form-group">
                        <label for="address">Private</label>
                        <input type="checkbox" name="private">
                    </div>
                    <input type="submit" value="Request" class="btn btn-secondary btn-block">
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
</section>

{% endblock %}