find_missing_people/contacts/urls.py
from django.urls import path

from . import views

app_name = 'contacts'

urlpatterns = [
    path('contact', views.contact, name='contact'),
]

find_missing_people/find_missing_people/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('listings/', include('listings.urls', namespace='listings')),
    path('', include('pages.urls', namespace='pages')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('contacts/', include('contacts.urls', namespace='contacts')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

find_missing_people/listings/urls.py
from django.urls import path

from . import views

app_name = 'listings'

urlpatterns = [
    path('', views.listings_all, name='listings_all'),
    path('<int:listing_id>/', views.detail, name='detail'),
    path('search/', views.search, name='search'),
]

find_missing_people/pages/urls.py
from django.urls import path

from . import views

app_name = 'pages'

urlpatterns = [
    path('', views.index, name='index'),
    path('map/', views.map, name='map'),
    path('request/', views.request, name='request'),
]

find_missing_people/listings/models.py
from datetime import datetime

from django.conf import settings
from django.db import models


class MissingPerson(models.Model):
    name = models.CharField(max_length=200)
    address = models.CharField(max_length=200)
    city = models.CharField(max_length=100)
    state = models.CharField(max_length=100)
    sex = models.CharField(max_length=1)
    age = models.IntegerField(blank=True)
    description = models.TextField(blank=True)
    photo_main = models.ImageField(upload_to='photos/%Y/%m/%d/')
    lat = models.DecimalField(max_digits=15, decimal_places=6, blank=True)
    lng = models.DecimalField(max_digits=15, decimal_places=6, blank=True)
    is_private = models.BooleanField(default=False)
    is_found = models.BooleanField(default=False)
    missing_date = models.DateTimeField(default=datetime.now, blank=True)
    list_date = models.DateTimeField(default=datetime.now, blank=True)
    is_accepted = models.BooleanField(default=False)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = 'MissingPeople'

    def __str__(self):
        return self.name

find_missing_people/listings/views.py
import datetime
import pytz

from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, render
from django.utils import timezone

from .choices import (end_year_choices, sex_choices, start_year_choices,
                      state_choices)
from .models import MissingPerson


def listings_all(request):
    listings = MissingPerson.objects.order_by('-list_date').filter(is_private=False, is_found=False, is_accepted=True)

    paginator = Paginator(listings, 3)
    page = request.GET.get('page')
    paged_listings = paginator.get_page(page)

    context = {
        'listings': paged_listings
    }

    return render(request, 'listings/listings.html', context)


def detail(request, listing_id):
    listing = get_object_or_404(MissingPerson, pk=listing_id)
    context = {
        'listing': listing
    }

    return render(request, 'listings/listing.html', context)


def search(request):
    query_list = MissingPerson.objects.order_by('-list_date').filter(is_accepted=True)
    start_year_tz = pytz.timezone('UTC') 
    start_year = start_year_tz.localize(datetime.datetime(2000, 1, 1, 0, 0))
    end_year_tz = pytz.timezone('UTC')
    end_year = timezone.now()

    if 'city' in request.GET:
        city = request.GET['city']
        if city:
            query_list = query_list.filter(city__iexact=city)

    if 'state' in request.GET:
        state = request.GET['state']
        if state:
            query_list = query_list.filter(state__iexact=state)

    if 'sex' in request.GET:
        sex = request.GET['sex']
        if sex:
            query_list = query_list.filter(sex__iexact=sex)

    if 'start_year' in request.GET:
        start_year = request.GET['start_year']
        if start_year:
            start_year = start_year_tz.localize(datetime.datetime(int(start_year), 1, 1, 0, 0))

    if 'end_year' in request.GET:
        end_year = request.GET['end_year']
        if end_year:
            end_year = end_year_tz.localize(datetime.datetime(int(end_year), 12, 31, 23, 59))

    query_list = query_list.filter(list_date__range=(start_year, end_year))
    context = {
        'state_choices': state_choices,
        'sex_choices': sex_choices,
        'start_year_choices': start_year_choices,
        'end_year_choices': end_year_choices,
        'listings': query_list,
        'values': request.GET
    }

    return render(request, 'listings/search.html', context)

find_missing_people/templates/listings/listing.html
{% extends 'base.html' %}

{% load static %}

{% block title %} | {{ listing.name }} {% endblock %}

{% block content %}

<section id="page-inner" class="py-5 text-white">
  <div class="container">
    <div class="row text-center">
      <div class="col-md-12">
        <h1 class="display-4">{{ listing.name }}</h1>
        <p class="lead">
          {{ listing.city }}, {{ listing.state }}
        </p>
      </div>
    </div>
  </div>
</section>

<section id="bc" class="mt-3">
  <div class="container">
    <nav>
      <ol class="breadcrumb">
        <li class="breadcrumb-item">
          <a href="{% url 'pages:index' %}">Home</a>
        </li>
        <li class="breadcrumb-item">
          <a href="{% url 'listings:listings_all' %}">Missing People</a>
        </li>
        <li class="breadcrumb-item active">{{ listing.name }}</li>
      </ol>
    </nav>
  </div>
</section>
{% include 'partials/_alerts.html' %}

<section id="listing" class="py-4">
  <div class="container">
    <a href="{% url 'listings:listings_all' %}" class="btn btn-light mb-4">Back To See All Missing People</a>
    <div class="row">
      <div class="col-md-9">
        <img src="{{ listing.photo_main.url }}" alt="" class="img-main img-fluid mb-3">
        <div class="row mb-5 fields">
          <div class="col-md-6">
            <ul class="list-group list-group-flush">
              <li class="list-group-item text-secondary">
                Requestor:
                <span class="float-right">{{ listing.user }}
                </span>
              </li>
              <li class="list-group-item text-secondary">
                Missing Date:
                <span class="float-right">{{ listing.missing_date }}</span>
              </li>
              <li class="list-group-item text-secondary">
                Age:
                <span class="float-right">{{ listing.age }}</span>
              </li>
              <li class="list-group-item text-secondary">
                Gender:
                <span class="float-right">{{ listing.sex }}</span>
              </li>
            </ul>
          </div>
        </div>

        <div class="row mb-5">
          <div class="col-md-12">
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Mollitia recusandae esse reiciendis officia omnis
            non rerum dicta
            cupiditate nostrum molestias deserunt aut minus inventore animi atque, consequuntur ad fugit. Possimus culpa
            blanditiis repellendus ipsa similique ullam, natus error dolor harum.
          </div>
        </div>
      </div>
      <div class="col-md-3">
        <div class="card mb-3">
          <div class="card-body">
            <h5 class="card-title">Requestor</h5>
            <h6 class="text-secondary">{{ listing.user }}</h6>
          </div>
        </div>
        <button class="btn-primary btn-block btn-lg" data-toggle="modal" data-target="#inquiryModal">Give
          Information</button>
      </div>
    </div>
  </div>
</section>

<div class="modal fade" id="inquiryModal" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="inquiryModalLabel">send Information</h5>
        <button type="button" class="close" data-dismiss="modal">
          <span>&times;</span>
        </button>
      </div>
      <div class="modal-body">
        {% if user.is_authenticated %}
        <form action="{% url 'contacts:contact' %}" method="POST">
          {% csrf_token %}
          <input type="hidden" name="user_id" value="{{ user.id }}">
          <input type="hidden" name="requestor_email" value="{{ listing.user.email }}">
          <input type="hidden" name="missing_person_id" value="{{ listing.id }}">
          <div class="form-group">
            <label for="requestor_name" class="col-form-label">Name To:</label>
            <input type="text" name="requestor_name" class="form-control"
              value="{{ listing.user.first_name }} {{ listing.user.last_name }}" disabled>
          </div>
          <div class="form-group">
            <label for="name" class="col-form-label">Name From:</label>
            <input type="text" name="name" class="form-control" value="{{ user.first_name }} {{ user.last_name }}"
              required>
          </div>
          <div class="form-group">
            <label for="email" class="col-form-label">Email:</label>
            <input type="email" name="email" class="form-control" value="{{ user.email }}" required>
          </div>
          <div class="form-group">
            <label for="phone" class="col-form-label">Phone:</label>
            <input type="text" name="phone" class="form-control">
          </div>
          <div class="form-group">
            <label for="message" class="col-form-label">Message:</label>
            <textarea name="message" class="form-control"></textarea>
          </div>
          <div class="form-group">
            <label for="date" class="col-form-label">When you saw:</label>
            <input type="date" name="date" value="2021-01-01" min="2000-01-01" max="2030-01-01">
          </div>
          <hr>
          <input type="submit" value="Send" class="btn btn-block btn-secondary">
        </form>
        {% else %}
        <div class="form-group">
          <label class="col-form-label">Please Login to send information.</label>
        </div>
        {% endif %}
      </div>
    </div>
  </div>
</div>

{% endblock %}

find_missing_people/templates/listings/listings.html
{% extends 'base.html' %}

{% load humanize %}

{% block title %} | List {% endblock %}

{% load static %}

{% block content %}

<section id="page-inner" class="py-5 text-white">
  <div class="container">
    <div class="row text-center">
      <div class="col-md-12">
        <h1 class="display-4">Missing People</h1>
        <p class="lead">Help Finding Missing People !</p>
      </div>
    </div>
  </div>
</section>

<section id="bc" class="mt-3">
  <div class="container">
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item">
          <a href="{% url 'pages:index' %}">
            <i class="fas fa-home"></i> Home</a>
        </li>
        <li class="breadcrumb-item active"> Missing People </li>
      </ol>
    </nav>
  </div>
</section>

<section id="listings" class="py-4">
  <div class="container">
    <div class="row">

      {% if listings %}
      {% for listing in listings %}
      <div class="col-md-6 col-lg-4 mb-4">
        <div class="card listing-preview">
          <img class="card-img-top" src="{{ listing.photo_main.url }}" alt="">
          <div class="card-body">
            <div class="listing-heading text-center">
              <h4 class="text-primary">{{ listing.name }}</h4>
              <p>
                <i class="fas fa-map-marker text-secondary"></i> {{ listing.city }}, {{ listing.state }} </p>
            </div>
            <div class="row py-2 text-secondary">
              <div class="col-12">
                <i class="fas fa-user"></i> {{ listing.user }}</div>
            </div>
            <div class="row text-secondary pb-2">
              <div class="col-6">
                <i class="fas fa-clock"></i> {{ listing.list_date | timesince }}</div>
            </div>
            <hr>
            <a href="{% url 'listings:detail' listing.id %}" class="btn btn-primary btn-block">More Info</a>
          </div>
        </div>
      </div>
      {% endfor %}
      {% else %}
      <div class="col-md-12">
        <p>No More Missing People</p>
      </div>
      {% endif %}

    </div>

    <div class="row">
      <div class="col-md-12">
        {% if listings.has_other_pages %}
        <ul class="pagination">
          {% if listings.has_previous %}
          <a href="?page={{listings.previous_page_number}}" class="page-link">&laquo;</a>

          {% else %}
          <li class="page-item disabled">
            <a class="page-link">&laquo;</a>
          </li>
          {% endif %}
          {% for i in listings.paginator.page_range %}
          {% if listings.number == i %}
          <li class="page-item active">
            <a class="page-link"> {{i}} </a>
          </li>
          {% else %}
          <li class="page-item">
            <a href="?page={{i}}" class="page-link">{{i}}</a>
          </li>
          {% endif %}
          {% endfor %}
          {% if listings.has_next %}
          <a href="?page={{listings.next_page_number}}" class="page-link">&raquo;</a>
          {% else %}
          <li class="page-item disabled">
            <a class="page-link">&raquo;</a>
          </li>
          {% endif %}
        </ul>
        {% endif %}
      </div>
    </div>
  </div>
</section>

{% endblock %}

find_missing_people/templates/listings/search.html
{% extends 'base.html' %} 

{% load humanize %}

{% block title %} | Search Results {% endblock %}

{% block content %}

<section id="page-inner" class="page-search text-white py-5">
    <div class="container">
      <div class="row text-center">
        <div class="col-md-12">
          <form action="{% url 'listings:search' %}">
            <!-- Form Row 1 -->
            <div class="form-row">
                <div class="col-md-4 mb-3">
                  <label class="sr-only">City</label>
                  <input type="text" name="city" class="form-control" placeholder="City" value="{{ values.city }}">
                </div>

                <div class="col-md-4 mb-3">
                  <label class="sr-only">State</label>
                  <select name="state" class="form-control">
                    <option selected="true" disabled="disabled">State (All)</option>
                    {% for abbrev, state in state_choices.items %}
                      <option value="{{ abbrev }}" {% if abbrev == values.state %} selected {% endif %} > {{ state }} </option>
                    {% endfor %}
                  </select>
                </div>

                <div class="col-md-4 mb-3">
                  <label class="sr-only">sex</label>
                  <select name="sex" class="form-control">
                    <option selected="true" disabled="disabled">Sex</option>
                    {% for letter, sex in sex_choices.items %}
                      <option value="{{ letter }}" {% if letter == values.sex %} selected {% endif %} > {{ sex }} </option>
                    {% endfor %}
                  </select>
                </div>
            </div>
            <!-- Form Row 2 -->
            <div class="form-row">
              <div class="col-md-6 mb-3">
                <label class="sr-only">start_year</label>
                <select name="start_year" class="form-control">
                  <option selected="true" disabled="disabled">start_year</option>
                  {% for start_year_key, start_year_val in start_year_choices.items %}
                    <option value="{{ start_year_key }}" {% if start_year_key == values.start_year %} selected {% endif %} > {{ start_year_val }} </option>
                  {% endfor %}
                </select>
              </div>
              <div class="col-md-6 mb-3">
                <label class="sr-only">end_year</label>
                <select name="end_year" class="form-control">
                  <option selected="true" disabled="disabled">end_year</option>
                  {% for end_year_key, end_year_val in end_year_choices.items %}
                    <option value="{{ end_year_key }}" {% if end_year_key == values.end_year %} selected {% endif %} > {{ end_year_val }} </option>
                  {% endfor %}
                </select>
              </div>
            </div>
            <button class="btn btn-secondary btn-block mt-4" type="submit">Submit form</button>
          </form>
        </div>
      </div>
    </div>
  </section>

  <!-- Breadcrumb -->
  <section id="bc" class="mt-3">
    <div class="container">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="{% url 'pages:index' %}">Home</a>
          </li>
          <li class="breadcrumb-item">
            <a href="{% url 'listings:listings_all' %}">Missing People</a>
          </li>
          <li class="breadcrumb-item active">Search Result</li>
        </ol>
      </nav>
    </div>
  </section>

  <!-- Listings -->
  <section id="listings" class="py-4">
    <div class="container">
      <div class="row">

        {% if listings %}
          {% for listing in listings %}
            <div class="col-md-6 col-lg-4 mb-4">
              <div class="card listing-preview">
                <img class="card-img-top" src="{{ listing.photo_main.url }}" alt="">
                <div class="card-body">
                  <div class="listing-heading text-center">
                    <h4 class="text-primary">{{ listing.name }}</h4>
                    <p>
                      <i class="fas fa-map-marker text-secondary"></i> {{ listing.city }}, {{ listing.state }} </p>
                  </div>
                  <div class="row py-2 text-secondary">
                    <div class="col-12">
                      <i class="fas fa-user"></i> {{ listing.user }}</div>
                  </div>
                  <div class="row text-secondary pb-2">
                    <div class="col-6">
                      <i class="fas fa-clock"></i> {{ listing.list_date | timesince }}</div>
                  </div>
                  <hr>
                  <a href="{% url 'listings:detail' listing.id %}" class="btn btn-primary btn-block">More Info</a>
                </div>
              </div>
            </div>
          {% endfor %}
        {% else %}
          <div class="col-md-12">
            <p>No Missing People Data In Server</p>
          </div>
        {% endif %}
      </div>
    </div>
  </section>

{% endblock %}