find_missing_people/accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views
from .forms import LoginForm

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html',
                                                form_class=LoginForm), name='login'),
    path('register/', views.register, name='register'),
    path('activate/<slug:uidb64>/<slug:token>/', views.activate, name='activate'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/accounts/login/'), name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
]

find_missing_people/find_missing_people/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('listings/', include('listings.urls', namespace='listings')),
    path('', include('pages.urls', namespace='pages')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('contacts/', include('contacts.urls', namespace='contacts')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

find_missing_people/listings/urls.py
from django.urls import path

from . import views

app_name = 'listings'

urlpatterns = [
    path('', views.listings_all, name='listings_all'),
    path('<int:listing_id>/', views.detail, name='detail'),
    path('search/', views.search, name='search'),
]

find_missing_people/pages/urls.py
from django.urls import path

from . import views

app_name = 'pages'

urlpatterns = [
    path('', views.index, name='index'),
    path('map/', views.map, name='map'),
    path('request/', views.request, name='request'),
]

find_missing_people/accounts/models.py
from django.db import models

find_missing_people/accounts/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User


class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control mb-3', 'placeholder': 'Username'}))
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={
            'class': 'form-control mb-3',
            'placeholder': 'Password',
            'id': 'password',
        }
    ))


class RegistrationForm(forms.ModelForm):
    first_name = forms.CharField(label='First Name', max_length=50, help_text='Required')
    last_name = forms.CharField(label='Last Name', max_length=50, help_text='Required')
    username = forms.CharField(label='Username', min_length=4, max_length=50, help_text='Required')
    email = forms.EmailField(max_length=100, help_text='Required',
                             error_messages={'required': 'Please, type a valid email'})
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password_confirm = forms.CharField(label='Password Confirm', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'email',)

    def clean_username(self):
        cleaned_name = self.cleaned_data['username'].lower()
        duplication = User.objects.filter(username=cleaned_name)

        if duplication.count():
            raise forms.ValidationError('Username already exists')

        return cleaned_name

    def clean_password_confirm(self):
        cleaned_data = self.cleaned_data

        if cleaned_data['password'] != cleaned_data['password_confirm']:
            raise forms.ValidationError('Passwords do not macth')

        return cleaned_data['password_confirm']

    def clean_email(self):
        cleaned_email = self.cleaned_data['email']
        duplication = User.objects.filter(email=cleaned_email)

        if duplication.exists():
            raise forms.ValidationError('Email already exists')

        return cleaned_email

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['first_name'].widget.attrs.update(
            {'class': 'form-control mb-3', 'placeholder': 'First Name'})
        self.fields['last_name'].widget.attrs.update(
            {'class': 'form-control mb-3', 'placeholder': 'Last Name'})
        self.fields['username'].widget.attrs.update(
            {'class': 'form-control mb-3', 'placeholder': 'Username'})
        self.fields['email'].widget.attrs.update(
            {'class': 'form-control mb-3', 'placeholder': 'Email'})
        self.fields['password'].widget.attrs.update(
            {'class': 'form-control mb-3', 'placeholder': 'Password'})
        self.fields['password_confirm'].widget.attrs.update(
            {'class': 'form-control mb-3', 'placeholder': 'Password Confirmation'})

find_missing_people/accounts/views.py
from collections import defaultdict

from django.contrib import auth, messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.sites.shortcuts import get_current_site
from django.shortcuts import redirect, render
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode

from contacts.models import Contact
from listings.models import MissingPerson

from .forms import RegistrationForm
from videos.models import ImagesFromVideo
from .tokens import account_activation_token


def register(request):
    if request.method == 'POST':
        regitseration_form = RegistrationForm(request.POST)

        if regitseration_form.is_valid():
            user = regitseration_form.save(commit=False)
            user.email = regitseration_form.cleaned_data['email']
            user.set_password(regitseration_form.cleaned_data['password'])
            user.is_active = False
            user.save()

            current_site = get_current_site(request)
            subject = 'Ativate Account'
            message = render_to_string('accounts/email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user)})
            user.email_user(subject=subject, message=message)
            return redirect('pages:index')
    else:
        regitseration_form = RegistrationForm()

    return render(request, 'accounts/register.html', {'form': regitseration_form})


def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except BaseException:
        return render(request, 'accounts/invalid.html')
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        auth.login(request, user)
        return redirect('accounts:dashboard')
    else:
        return render(request, 'accounts/invalid.html')


@login_required
def dashboard(request):
    if request.method == 'POST':
        if 'correct' in request.POST:
            missing_person_id, image_id = request.POST['correct'].split(',')
            request_info = MissingPerson.objects.get(id=missing_person_id)
            request_info.is_found = True
            request_info.save()

        elif 'wrong' in request.POST:
            missing_person_id, image_id = request.POST['wrong'].split(',')

        filtered_image = ImagesFromVideo.objects.order_by('-date').filter(user=request.user.id, missing_person=missing_person_id).get(id=image_id)
        filtered_image.delete()

    user_contacts = Contact.objects.order_by('-contact_date').filter(user_id=request.user.id)
    user_requests = MissingPerson.objects.order_by('-list_date').filter(user_id=request.user.id, is_accepted=True)
    user_taken_images = ImagesFromVideo.objects.order_by('-date').filter(user_id=request.user.id)
    image_dictionary = defaultdict(list)

    for image in user_taken_images:
        _id, missing_person_id, image_url = image.id, image.missing_person_id, image.photo.url
        image_dictionary[missing_person_id].append((image_url, _id))

    context = {
        'contacts': user_contacts,
        'requests': user_requests,
        'images': image_dictionary
    }
    return render(request, 'accounts/dashboard.html', context)

find_missing_people/templates/accounts/dashboard.html
{% extends 'base.html' %}

{% load static %}
{% load custom_tags %}

{% block title %} | Dashboard {% endblock %}

{% block content %}

<section id="page-inner" class="py-5 text-white">
  <div class="container">
    <div class="row text-center">
      <div class="col-md-12">
        <h1 class="display-4">User Dashboard</h1>
        <p class="lead">Manage your requests and check if missing people are found</p>
      </div>
    </div>
  </div>
</section>

<section id="bc" class="mt-3">
    <div class="container">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="{% url 'pages:index' %}">
              <i class="fas fa-home"></i> Home</a>
          </li>
          <li class="breadcrumb-item active"> Dashboard</li>
        </ol>
      </nav>
    </div>
  </section>

{% include 'partials/_alerts.html' %}

<section id="dashboard" class="py-4">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h2>Welcome {{ user.username }}</h2>
          {% if requests %}
            <p>Here are the missing people that you have requested</p>
            <table class="table">
              <thead>
                <tr>
                  <th scope="col">#</th>
                  <th scope="col">Missing Person</th>
                  <th scope="col">Is Found</th>
                  <th scope="col">Infomation</th>
                  <th scope="col">Images</th>
                </tr>
              </thead>
              <tbody>
                {% for request in requests %}
                  <tr>
                    <td>{{ request.id }}</td>
                    <td>{{ request.name }}</td>
                    <td>{{ request.is_found }}</td>
                    <td>
                      <a class="btn btn-light" href="{% url 'listings:detail' request.id %}">View Person</a>
                    </td>
                    <td>
                      <button class="btn btn-light" data-toggle="modal" data-target="#images_{{request.id}}">View Images</button>
                        <div class="modal" id="images_{{request.id}}" role="dialog">
                          <div class="modal-dialog">
                            <div class="modal-content">
                              <div class="modal-header">
                                <h5 class="modal-title" id="images_{{request.id}}Label">Images</h5>
                                <button type="button" class="close" data-dismiss="modal">
                                  <span>&times;</span>
                                </button>
                              </div>
                              <div class="modal-body">    
                                {% if request.id in images %}
                                  {% for image, id in images|get_item:request.id %}
                                    <div class="form-group">
                                      <label class="col-form-label mySlides_{{ request.id }}"><img src="{{ image }}" alt="">
                                      <form action="{% url 'accounts:dashboard' %}" method="post">
                                        {% csrf_token %}
                                        <button class="btn btn-success btn-answer" name='correct' value='{{request.id}},{{id}}' type="submit">correct</button>
                                        <button class="btn btn-danger btn-answer" name='wrong' value='{{request.id}},{{id}}' type="submit">wrong</button>
                                      </form> 
                                    </label>
                                    </div>
                                  {% endfor %}
                                    <button class="btn btn-primary" onclick="plusDivs(-1, '{{request.id}}')">&#10094; Prev</button>
                                    <button class="btn btn-primary" onclick="plusDivs(1, '{{request.id}}')">Next &#10095;</button>
                                {% else %}
                                <div class="form-group">
                                  <label class="col-form-label">There are not images.</label>
                                </div> 
                                {% endif %}
                              </div>
                            </div>
                          </div>
                        </div>
                    </td>
                  </tr>
                {% endfor %}
              </tbody>
            </table>
          {% else %}
            <p> You don't have any requests. </p>
          {% endif %}
          {% if contacts %}
            <table class="table">
              <thead>
                <tr>
                  <th scope="col">#</th>
                  <th scope="col">Missing Person</th>
                  <th scope="col">From who</th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
                {% for contact in contacts %}
                  <tr>
                    <td>{{ contact.id }}</td>
                    <td>{{ contact.missing_person_name}}</td>
                    <td>{{ contact.from_name }}</td>
                    <td>
                      <button class="btn btn-light" data-toggle="modal" data-target="#message">View Message</button>
                    </td>
                  </tr>
                  <div class="modal" id="message" role="dialog">
                    <div class="modal-dialog">
                      <div class="modal-content">
                        <div class="modal-header">
                          <h5 class="modal-title" id="messageLabel">Message</h5>
                          <button type="button" class="close" data-dismiss="modal">
                            <span>&times;</span>
                          </button>
                        </div>
                        <div class="modal-body">
                          <div class="form-group">
                            <label class="col-form-label">{{ contact.message }}</label>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                {% endfor %}
              </tbody>
            </table>
          {% endif %}
        </div>
      </div>
    </div>
  </section>
  <script src="{% static 'js/slides.js' %}"></script>

{% endblock %}

find_missing_people/templates/accounts/email.html
{% autoescape off %}

Hello {{ user.username }},

This is univerChain auto mailing system.

Please, click link below to activate yout account.

http://{{ domain }}{% url 'accounts:activate' uidb64=uid token=token %}

{% endautoescape %}

find_missing_people/templates/accounts/invalid.html
{% extends 'base.html' %}

{% load static %}

{% block title %} | Register {% endblock %}

{% block content %}

<div class="container p-5">
    <div class="row p-5">
        <div class="col-md-6 mx-auto">
            <div class="text-black">
                <h1 class="text-center">Invalid User</h1>
            </div>
        </div>
    </div>
</div>

{% endblock %}

find_missing_people/templates/accounts/login.html
{% extends 'base.html' %}

{% load static %}

{% block title %} | Login {% endblock %}

{% block content %}

<section id="login" class="bg-light py-5">
    <div class="container">
      <div class="row">
        <div class="col-md-6 mx-auto">
          <div class="card">
            <div class="card-header bg-primary text-white">
              <h4>
                <i class="fas fa-sign-in-alt"></i> Login</h4>
            </div>
            <div class="card-body">
                <form action="{% url 'accounts:login' %}" method="POST">
                  {% csrf_token %}
                  {% if form.errors %}
                    <div class="alert alert-primary" role="alert">
                      Error: Username or Password is not correct.
                    </div>
                  {% endif %}
                  <div class="form-group">
                    <label for="username">{{ form.username.label }}<span class="text-muted small">
                      </span></label>
                    {{ form.username }}
                  </div>
                  <div class="form-group">
                    <label for="password">{{ form.password.label }}<span class="text-muted small">
                      </span> </label> 
                    {{ form.password }}
                  </div>
                  <input type="submit" value="Login" class="btn btn-secondary btn-block">
                </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  
{% endblock %}

find_missing_people/templates/accounts/register.html
{% extends 'base.html' %}

{% load static %}

{% block title %} | Register {% endblock %}

{% block content %}

<section id="register" class="bg-light py-5">
  <div class="container">
    <div class="row">
      <div class="col-md-6 mx-auto">
        <div class="card">
          <div class="card-header bg-primary text-white">
            <h4>
              <i class="fas fa-user-plus"></i> Register</h4>
          </div>
          <div class="card-body">
            {% if form.errors %}
            <div id="errors">
              <div class="inner">
                <p>There were some errors in the information you entered. Please correct the
                  following:</p>
                <ul>
                  {% for field in form %}
                  {% if field.errors %}<li>{{ field.label }}: {{ field.errors|striptags }}</li>
                  {% endif %}
                  {% endfor %}
                </ul>
              </div>
            </div>
            {% endif %}
            <form action="{% url 'accounts:register' %}" method="POST">
              {% csrf_token %}
              <div class="form-group">
                <label for="first_name">{{ form.first_name.label }}<span class="text-muted small">
                </span></label>
                {{ form.first_name }}
              </div>
              <div class="form-group">
                <label for="last_name">{{ form.last_name.label }}<span class="text-muted small">
                </span></label>
                {{ form.last_name }}
              </div>
              <div class="form-group">
                <label for="username">{{ form.username.label }}<span class="text-muted small">
                  </span></label>
                {{ form.username }}
              </div>
              <div class="form-group">
                <label for="email">{{ form.email.label }}<span class="text-muted small">
                  </span></label>
                {{ form.email }}
              </div>
              <div class="form-group">
                <label for="password2">{{ form.password.label }}<span class="text-muted small">
                  </span></label>
                {{ form.password }}
              </div>
              <div class="form-group">
                <label for="password">{{ form.password_confirm.label }}<span class="text-muted small">
                  </span></label>
                {{ form.password_confirm }}
              </div>
              <div class="form-group">
                <label for="etherAccount">{{ form.univercoin_account.label }}<span class="text-muted small">
                  </span></label>
                {{ form.univercoin_account }}
              </div>
              <input type="submit" value="Register" class="btn btn-secondary btn-block">
              <p class="text-center p-2">
                <a href="{% url 'accounts:login' %}"><u>Already have an account?</u></a>
              </p>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>  

{% endblock %}