find_missing_people/accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views
from .forms import LoginForm

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html',
                                                form_class=LoginForm), name='login'),
    path('register/', views.register, name='register'),
    path('activate/<slug:uidb64>/<slug:token>/', views.activate, name='activate'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/accounts/login/'), name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
]

find_missing_people/find_missing_people/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('listings/', include('listings.urls', namespace='listings')),
    path('', include('pages.urls', namespace='pages')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('contacts/', include('contacts.urls', namespace='contacts')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

find_missing_people/listings/urls.py
from django.urls import path

from . import views

app_name = 'listings'

urlpatterns = [
    path('', views.listings_all, name='listings_all'),
    path('<int:listing_id>/', views.detail, name='detail'),
    path('search/', views.search, name='search'),
]

find_missing_people/pages/urls.py
from django.urls import path

from . import views

app_name = 'pages'

urlpatterns = [
    path('', views.index, name='index'),
    path('map/', views.map, name='map'),
    path('request/', views.request, name='request'),
]

find_missing_people/templates/partials/_alerts.html
{% if messages %}
    {% for message in messages %}
    <div id="message" class="container">
        <div class="alert alert-{{message.tags}} alert-dismissible text-center" rol="alert">
            <button type="button" class="close" data-dimiss="alert"><span aria-hidden="true">&times;</span></button>
        <strong>
            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                Error:
            {% else %}
                {{ message.tags|title }}
            {% endif %}
        </strong>
        {{ message }}
        </div>
    </div>
    {% endfor %}
{% endif %}

find_missing_people/templates/partials/_footer.html
<!-- Footer -->
<footer id="main-footer" class="py-4 bg-primary text-white text-center">
    Copyright &copy;
    <span class="year"></span> Find Missing People
</footer>

find_missing_people/templates/partials/_navbar.html
{% load static %}

<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-dark bg-primary sticky-top">
<div class="container">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup">
    <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <ul class="navbar-nav">
        <li
            {% if '/' == request.path %}
                class="nav-item active mr-3"
            {% else %}
                class="nav-item mr-3"
            {% endif %}
        >
        <a class="nav-link" href="{% url 'pages:index' %}">Home</a>
        </li>
        <li 
            {% if 'map' in request.path %}
                class="nav-item active mr-3"
            {% else %}
                cla ss="nav-item mr-3"
            {% endif %}
        >
        <a class="nav-link" href="{% url 'pages:map' %}">Map</a>
        </li>
        <li 
        {% if 'listings_all' in request.path %}
            class="nav-item active mr-3"
        {% else %}
            cla ss="nav-item mr-3"
        {% endif %}
        >
        <a class="nav-link" href="{% url 'listings:listings_all' %}">Missing People</a>
        </li>
    </ul>

    <ul class="navbar-nav ml-auto">
        {% if user.is_authenticated %}
            <li
                {% if 'dashboard' in request.path %}
                    class="nav-item active mr-3"
                {% else %}
                    cla ss="nav-item mr-3"
                {% endif %}
                >
                <a class="nav-link" href="{% url 'accounts:dashboard' %}">
                    Welcome {{ user.username }} (Dashboard)</a>
            </li>
            <li 
                {% if 'request' in request.path %}
                    class="nav-item active mr-3"
                {% else %}
                    cla ss="nav-item mr-3"
                {% endif %}
                >
                <a class="nav-link" href="{% url 'pages:request' %}">Request</a>
            </li>
            <li class="nav-item mr-3">
                <a href="javascript:{document.getElementById('logout').submit()}" class="nav-link">
                    <i class="fas fa-sign-out-alt"></i> Logout
                </a>
                <form action="{% url 'accounts:logout' %}" method="POST" id="logout">
                    {% csrf_token %}
                    <input type="hidden">
                </form>
            </li>

        {% else %}
            <li
                {% if 'register' in request.path %}
                    class="nav-item active mr-3"
                {% else %}
                    cla ss="nav-item mr-3"
                {% endif %}
                >
                <a class="nav-link" href="{% url 'accounts:register' %}">
                    <i class="fas fa-user-plus"></i> Register</a>
            </li>
            <li
                {% if 'login' in request.path %}
                    class="nav-item active mr-3"
                {% else %}
                    cla ss="nav-item mr-3"
                {% endif %}
                >
                <a class="nav-link" href="{% url 'accounts:login' %}">
                    <i class="fas fa-sign-in-alt"></i>

                    Login</a>
            </li>
        {% endif %}
    </ul>
    </div>
</div>
</nav>

find_missing_people/templates/partials/_topbar.html
<!-- Top Bar -->
<section id="top-bar" class="p-3">
    <div class="container">
        <div class="row">
        <div class="col-md-4">
        </div>
        <div class="col-md-4">
        </div>
        <div class="col-md-4">
            <i class="fas fa-envelope-open"></i> sammiee5311@gmail.com
        </div>
        </div>
    </div>
    </section>